# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check code style
        run: |
          pip install "yapf==0.30.0"
          bash format.sh --test

  code_docstring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install software
        run: |
          sudo apt update && sudo apt install -y bc
          pip install "docstr-coverage==2.3.0"
      - name: Get post-PR docstring coverage
        run: |
          after=$(docstr-coverage --percentage-only --fail-under 0 metadrive/)
          echo "after=$after" >> "$GITHUB_ENV"
      - name: Checkout the main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Get pre-PR docstring coverage
        run: |
          before=$(docstr-coverage --percentage-only --fail-under 0 metadrive/)
          echo "before=$before" >> "$GITHUB_ENV"
      - name: Check if docstring coverage decreases
        run: |
          printf 'Docstring coverage before pull request: %s%%\n' "$before"
          printf 'Docstring coverage after pull request: %s%%\n' "$after"
          improvement=$(echo "$after - $before" | bc -l)
          if (( $(echo "$after < $before" |bc -l) )); then
            printf 'Docstring coverage check failed! We require the docstring coverage to be non-decreasing after PR. You have decreased the coverage by: %s%%\n' "$improvement"
            exit 1
          fi
          printf 'Docstring coverage check successful! We require the docstring coverage to be non-decreasing after PR. You have changed the coverage by: %s%%\n' "$improvement"
          message='Docstring coverage check successful! You have changed the coverage from ${before} to ${after} by ${improvement}.'
          printf $message
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "${message}"
            })




  test_functionality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_functionality

  test_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install gym
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_env

  test_policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_policy

  test_component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_component

  test_export_record_scenario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_export_record_scenario

  test_ipynb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pip install nbmake pytest-xdist
          mkdir ./tests/test_ipynb
          cp ./examples/Basic_MetaDrive_Usages.ipynb ./tests/test_ipynb/
          pytest --nbmake -n=auto ./tests/test_ipynb/

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          file: ./metadrive/coverage.xml
#          fail_ci_if_error: true
