# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check code style
        run: |
          pip install "yapf==0.30.0"
          bash format.sh --test

  test_functionality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_functionality

  test_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install gym
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_env

  test_policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_policy

  test_component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_component

  test_export_record_scenario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_export_record_scenario

  test_ipynb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pip install nbmake pytest-xdist
          mkdir ./tests/test_ipynb
          cp ./examples/Basic_MetaDrive_Usages.ipynb ./tests/test_ipynb/
          pytest --nbmake -n=auto ./tests/test_ipynb/

  test_ros:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
    steps:
      - name: Set up ROS2 humble
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: checkout code
        uses: actions/checkout@v2
      - name: Blackbox tests
        run: |
          pip install pyzmq
          ls -al
          pip install -e .
          python -m metadrive.pull_asset
          sudo rosdep init
          sudo rosdep update
          cd bridges/ros_bridge
          rosdep install --from-paths src --ignore-src -y
          colcon build
          source install/setup.bash
          nohup ros2 launch metadrive_example_bridge metadrive_example_bridge.launch.py > ros.txt 2>&1 &
          
          python ros_socket_server.py --test

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          file: ./metadrive/coverage.xml
#          fail_ci_if_error: true
