# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check code style
        run: |
          pip install "yapf==0.30.0"
          bash format.sh --test

  test_functionality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_functionality

  test_environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install gym
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_env

  test_policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_policy

  test_component:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_component

  test_export_record_scenario:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests/test_export_record_scenario

  test_ipynb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          python -m metadrive.pull_asset
          pip install pytest
          pip install pytest-cov
          pip install ray
          cd metadrive/
          pip install nbmake pytest-xdist
          cache store
          mkdir ./tests/test_ipynb
          cp ./examples/Basic_MetaDrive_Usages.ipynb ./test/tests_ipynb
          pytest --nbmake -n=auto ./test/tests_ipynb

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          file: ./metadrive/coverage.xml
#          fail_ci_if_error: true
